"use client";

import { useCallback, useEffect, useState, useSyncExternalStore } from "react";
import { useRouter } from "next/navigation";
import { Brain, Check, Loader2, Plus } from "lucide-react";
import {
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { Badge } from "@/components/ui/badge";
import { chatService, contextService } from "@/lib/services";
import { toast } from "@/lib/toast";
import { getRouteUiSnapshot, subscribeRouteUi } from "@/lib/route-ui-store";

const PENDING_CONTEXT_IDS_KEY = "pending_new_chat_context_ids";
const PENDING_FOLDER_ID_KEY = "pending_new_chat_folder_id";

type ContextOption = {
  id: number;
  title?: string;
  isAutoGenerated?: boolean;
  isAutoSelected?: boolean;
};

function getFolderIdHint(): number | null {
  try {
    const raw = localStorage.getItem(PENDING_FOLDER_ID_KEY);
    const parsed = raw ? Number(raw) : NaN;
    if (!Number.isNaN(parsed)) return parsed;
  } catch {
    // ignore localStorage issues
  }
  try {
    const params = new URLSearchParams(window.location.search);
    const raw = params.get("folderId");
    if (!raw) return null;
    const parsed = Number(raw);
    return Number.isNaN(parsed) ? null : parsed;
  } catch {
    return null;
  }
}

export function ContextPickerMenu({ onNavigateAway }: { onNavigateAway?: () => void }) {
  const router = useRouter();
  const activeChatId = useSyncExternalStore(
    subscribeRouteUi,
    () => getRouteUiSnapshot().activeChatId,
    () => null,
  );

  const [loading, setLoading] = useState(true);
  const [contexts, setContexts] = useState<ContextOption[]>([]);
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      let folderId: number | null = null;
      if (activeChatId) {
        try {
          const chatRes = await chatService.getById(activeChatId);
          folderId = chatRes.data?.data?.folderId ?? null;
        } catch {
          folderId = null;
        }
      } else {
        folderId = getFolderIdHint();
      }

      const sidebarRes = await contextService.getSidebar(
        folderId ? { folderId: String(folderId) } : undefined,
      );
      const payload = sidebarRes.data?.data || {
        globalContexts: [],
        folderContexts: [],
        customContexts: [],
      };

      const seen = new Set<number>();
      const merged: ContextOption[] = [
        ...(payload.globalContexts || []),
        ...(payload.folderContexts || []),
        ...(payload.customContexts || []),
      ].filter((ctx: ContextOption) => {
        if (!ctx?.id || seen.has(ctx.id)) return false;
        seen.add(ctx.id);
        return true;
      });
      setContexts(merged);

      if (activeChatId) {
        const selectedRes = await chatService.getContexts(activeChatId);
        setSelectedIds(selectedRes.data?.data?.contextIds || []);
      } else {
        const stored = localStorage.getItem(PENDING_CONTEXT_IDS_KEY);
        if (stored) {
          try {
            const parsed = JSON.parse(stored);
            setSelectedIds(
              Array.isArray(parsed)
                ? parsed.map((id: unknown) => Number(id)).filter((id) => !Number.isNaN(id))
                : [],
            );
          } catch {
            setSelectedIds([]);
          }
        } else {
          const defaultGlobalIds = (payload.globalContexts || [])
            .filter((ctx: ContextOption) => ctx.isAutoSelected)
            .map((ctx: ContextOption) => ctx.id);
          const defaultFolderIds = folderId
            ? (payload.folderContexts || []).map((ctx: ContextOption) => ctx.id)
            : [];
          setSelectedIds(Array.from(new Set([...defaultGlobalIds, ...defaultFolderIds])));
        }
      }
    } catch {
      setContexts([]);
      setSelectedIds([]);
    } finally {
      setLoading(false);
    }
  }, [activeChatId]);

  useEffect(() => {
    void load();
  }, [load]);

  const toggleContext = useCallback(
    async (ctx: ContextOption) => {
      if (saving || ctx.isAutoGenerated) return;
      const next = selectedIds.includes(ctx.id)
        ? selectedIds.filter((id) => id !== ctx.id)
        : [...selectedIds, ctx.id];
      setSelectedIds(next);

      if (!activeChatId) {
        try {
          localStorage.setItem(PENDING_CONTEXT_IDS_KEY, JSON.stringify(next));
        } catch {
          // ignore localStorage issues
        }
        return;
      }

      setSaving(true);
      try {
        await chatService.replaceContexts(activeChatId, next);
      } catch {
        toast.error("Failed to update chat contexts");
        await load();
      } finally {
        setSaving(false);
      }
    },
    [activeChatId, load, saving, selectedIds],
  );

  return (
    <DropdownMenuSub>
      <DropdownMenuSubTrigger
        className="gap-2 focus:bg-muted cursor-pointer rounded-md py-2"
        onSelect={(e) => e.preventDefault()}
      >
        <div className="w-4 flex justify-center">
          <Brain className="w-4 h-4 text-muted-foreground" />
        </div>
        <span>Context</span>
        {selectedIds.length > 0 && (
          <Badge
            variant="secondary"
            className="ml-auto mr-1 text-[10px] px-1.5 py-0 h-4 rounded-md"
          >
            {selectedIds.length}
          </Badge>
        )}
      </DropdownMenuSubTrigger>
      <DropdownMenuSubContent className="w-[260px] max-h-[320px] overflow-y-auto p-2 rounded-xl">
        {loading ? (
          <div className="flex items-center justify-center gap-2 px-2 py-4 text-xs text-muted-foreground">
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
            Loading contexts...
          </div>
        ) : contexts.length === 0 ? (
          <div className="px-2 py-3 text-xs text-muted-foreground">
            No contexts yet
          </div>
        ) : (
          contexts.map((ctx) => (
            <DropdownMenuItem
              key={ctx.id}
              className="gap-2 focus:bg-muted cursor-pointer rounded-md py-2"
              disabled={ctx.isAutoGenerated}
              title={ctx.isAutoGenerated ? "System generated context — always included" : undefined}
              onSelect={(e) => {
                e.preventDefault();
                void toggleContext(ctx);
              }}
            >
              <div className="w-4 flex justify-center">
                {(ctx.isAutoGenerated || selectedIds.includes(ctx.id)) && (
                  <Check className="w-3 h-3 text-primary" />
                )}
              </div>
              <span className="truncate">{ctx.title || "Untitled context"}</span>
            </DropdownMenuItem>
          ))
        )}

        <DropdownMenuSeparator className="my-2" />

        <DropdownMenuItem
          className="gap-2 cursor-pointer rounded-md py-2 text-primary focus:text-primary"
          onSelect={(e) => {
            e.preventDefault();
            onNavigateAway?.();
            router.push("/profile/contexts");
          }}
        >
          <Plus className="w-4 h-4" />
          <span>Create more</span>
        </DropdownMenuItem>
      </DropdownMenuSubContent>
    </DropdownMenuSub>
  );
}
