"use client";

import { useRouter } from "next/navigation";
import { Brain, Check, Loader2, Plus } from "lucide-react";
import {
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { Badge } from "@/components/ui/badge";
import { useContextPicker } from "@/components/chat/use-context-picker";

export function ContextPickerMenu({ onNavigateAway }: { onNavigateAway?: () => void }) {
  const router = useRouter();
  const { loading, contexts, selectedIds, toggleContext } = useContextPicker();

  return (
    <DropdownMenuSub>
      <DropdownMenuSubTrigger
        className="gap-2 focus:bg-muted cursor-pointer rounded-md py-2"
        onSelect={(e) => e.preventDefault()}
      >
        <div className="w-4 flex justify-center">
          <Brain className="w-4 h-4 text-muted-foreground" />
        </div>
        <span>Context</span>
        {selectedIds.length > 0 && (
          <Badge
            variant="secondary"
            className="ml-auto mr-1 text-[10px] px-1.5 py-0 h-4 rounded-md"
          >
            {selectedIds.length}
          </Badge>
        )}
      </DropdownMenuSubTrigger>
      <DropdownMenuSubContent className="w-[260px] max-h-[320px] overflow-y-auto p-2 rounded-xl">
        {loading ? (
          <div className="flex items-center justify-center gap-2 px-2 py-4 text-xs text-muted-foreground">
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
            Loading contexts...
          </div>
        ) : contexts.length === 0 ? (
          <div className="px-2 py-3 text-xs text-muted-foreground">
            No contexts yet
          </div>
        ) : (
          contexts.map((ctx) => (
            <DropdownMenuItem
              key={ctx.id}
              className="gap-2 focus:bg-muted cursor-pointer rounded-md py-2"
              disabled={ctx.isAutoGenerated}
              title={ctx.isAutoGenerated ? "System generated context — always included" : undefined}
              onSelect={(e) => {
                e.preventDefault();
                void toggleContext(ctx);
              }}
            >
              <div className="w-4 flex justify-center">
                {(ctx.isAutoGenerated || selectedIds.includes(ctx.id)) && (
                  <Check className="w-3 h-3 text-primary" />
                )}
              </div>
              <span className="truncate">{ctx.title || "Untitled context"}</span>
            </DropdownMenuItem>
          ))
        )}

        <DropdownMenuSeparator className="my-2" />

        <DropdownMenuItem
          className="gap-2 cursor-pointer rounded-md py-2 text-primary focus:text-primary"
          onSelect={(e) => {
            e.preventDefault();
            onNavigateAway?.();
            router.push("/profile/contexts");
          }}
        >
          <Plus className="w-4 h-4" />
          <span>Create more</span>
        </DropdownMenuItem>
      </DropdownMenuSubContent>
    </DropdownMenuSub>
  );
}
