import prisma from "@root/prisma.js";
import { ApiError } from "@/utils/ApiError.js";
import STATUS_CODES from "@/utils/statusCodes.js";
import { languageFromPath, normalizeCodePath } from "@/modules/code-workspace/code-workspace.parser.js";
import {
  readFiles,
  snapshotUserEditsIfDirty,
  snapshotVersion,
} from "@/modules/code-workspace/code-workspace.service.js";
import { MAX_FILE_CHARS, MAX_FILES_PER_PROJECT } from "@/modules/code-workspace/code-workspace.types.js";
import { getInstallationToken, isGithubConfigured } from "./github.app.js";
import { githubJson, githubRaw, GithubHttpError } from "./github.api.js";
import {
  BINARY_EXTENSIONS,
  BLOB_FETCH_CONCURRENCY,
  MAX_INLINE_TREE_BYTES,
  REMOTE_AHEAD_MARK,
  type GithubPullResultDto,
  type GithubPushResultDto,
} from "./github.types.js";

/**
 * Mirrors a CodeProject to a GitHub repo through the Git Data API.
 *
 * One CodeProjectVersion == one commit. The commit tree is built WITHOUT a
 * base_tree, so it is exactly the project's current files: a file the AI
 * deleted disappears from GitHub too. That makes CodeFile the source of truth
 * — and is also why remote-ahead detection below is essential, or an edit made
 * on github.com would be silently wiped by the next push.
 */

interface LinkContext {
  id: number;
  projectId: number;
  owner: string;
  repo: string;
  branch: string;
  autoPush: boolean;
  lastCommitSha: string | null;
  connection: { installationId: string; isActive: boolean };
}

/* ------------------------------------------------------------------ *
 * Serialisation: one sync per project at a time, per process.
 * Every push reads the DB fresh, so a queued push just picks up the latest
 * state — running two concurrently would only race on the branch ref.
 * ------------------------------------------------------------------ */

const queues = new Map<number, Promise<unknown>>();

function serialise<T>(projectId: number, task: () => Promise<T>): Promise<T> {
  const previous = queues.get(projectId) ?? Promise.resolve();
  const next = previous.catch(() => undefined).then(task);
  queues.set(projectId, next);
  next.finally(() => {
    if (queues.get(projectId) === next) queues.delete(projectId);
  }).catch(() => undefined);
  return next;
}

async function loadLink(projectId: number): Promise<LinkContext | null> {
  return prisma.githubRepoLink.findUnique({
    where: { projectId },
    select: {
      id: true,
      projectId: true,
      owner: true,
      repo: true,
      branch: true,
      autoPush: true,
      lastCommitSha: true,
      connection: { select: { installationId: true, isActive: true } },
    },
  });
}

async function setSyncState(linkId: number, state: "IDLE" | "SYNCING" | "ERROR", extra: Record<string, unknown> = {}) {
  await prisma.githubRepoLink.update({
    where: { id: linkId },
    data: { syncState: state, ...(state === "ERROR" ? {} : { lastError: null }), ...extra },
  });
}

/* ------------------------------------------------------------------ *
 * Commit message
 * ------------------------------------------------------------------ */

function buildCommitMessage(params: {
  version: number;
  title: string;
  plan: string | null;
  changedPaths: string[];
  source: string;
}): string {
  const planLine = params.plan?.split("\n").map((l) => l.trim()).find(Boolean);
  const subject = `v${params.version}: ${(planLine || `Update ${params.title}`).slice(0, 72)}`;

  const written = params.changedPaths.filter((p) => !p.startsWith("-"));
  const removed = params.changedPaths.filter((p) => p.startsWith("-")).map((p) => p.slice(1));
  const lines: string[] = [];
  for (const p of written.slice(0, 30)) lines.push(`- ${p}`);
  if (written.length > 30) lines.push(`- …and ${written.length - 30} more`);
  for (const p of removed.slice(0, 10)) lines.push(`- removed: ${p}`);

  const origin = params.source === "USER" ? "Manual edits" : "Generated by ColabAI";
  return [subject, lines.length ? `\n${lines.join("\n")}` : "", `\n${origin}`].join("\n").replace(/\n{3,}/g, "\n\n");
}

/* ------------------------------------------------------------------ *
 * Push
 * ------------------------------------------------------------------ */

interface RemoteHead {
  /** null when the repo has no commits at all, or the branch does not exist yet. */
  sha: string | null;
  repoEmpty: boolean;
}

async function readRemoteHead(token: string, owner: string, repo: string, branch: string): Promise<RemoteHead> {
  const res = await githubRaw<{ object: { sha: string } }>(
    `/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(branch)}`,
    { token },
  );
  if (res.ok) return { sha: res.data!.object.sha, repoEmpty: false };
  // A repo with zero commits answers 409 to every git-data call.
  if (res.status === 409) return { sha: null, repoEmpty: true };
  if (res.status === 404) return { sha: null, repoEmpty: false };
  throw new GithubHttpError("Could not read the repository", STATUS_CODES.BAD_REQUEST, res.status);
}

/**
 * The Git Data API cannot write to a repository with no commits. The Contents
 * API can, so it creates the very first commit (with a real project file, not
 * a placeholder) and the full tree commit then builds on top of it.
 */
async function bootstrapEmptyRepo(
  token: string,
  owner: string,
  repo: string,
  file: { path: string; content: string },
): Promise<string> {
  const created = await githubJson<{ commit: { sha: string } }>(
    `/repos/${owner}/${repo}/contents/${file.path.split("/").map(encodeURIComponent).join("/")}`,
    {
      token,
      method: "PUT",
      body: {
        message: "Initial commit",
        content: Buffer.from(file.content, "utf8").toString("base64"),
      },
    },
  );
  return created.commit.sha;
}

async function createBlob(token: string, owner: string, repo: string, content: string): Promise<string> {
  const blob = await githubJson<{ sha: string }>(`/repos/${owner}/${repo}/git/blobs`, {
    token,
    method: "POST",
    body: { content: Buffer.from(content, "utf8").toString("base64"), encoding: "base64" },
  });
  return blob.sha;
}

async function createTree(
  token: string,
  owner: string,
  repo: string,
  files: { path: string; content: string }[],
): Promise<string> {
  const totalBytes = files.reduce((n, f) => n + Buffer.byteLength(f.content, "utf8"), 0);
  const useBlobs = totalBytes > MAX_INLINE_TREE_BYTES;

  const entries = await mapLimit(files, BLOB_FETCH_CONCURRENCY, async (f) => {
    // Empty inline `content` is unreliable on the trees endpoint; a blob is always safe.
    if (useBlobs || f.content.length === 0) {
      return { path: f.path, mode: "100644", type: "blob", sha: await createBlob(token, owner, repo, f.content) };
    }
    return { path: f.path, mode: "100644", type: "blob", content: f.content };
  });

  const tree = await githubJson<{ sha: string }>(`/repos/${owner}/${repo}/git/trees`, {
    token,
    method: "POST",
    body: { tree: entries },
  });
  return tree.sha;
}

async function mapLimit<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const results = new Array<R>(items.length);
  let cursor = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const index = cursor++;
      results[index] = await fn(items[index]);
    }
  });
  await Promise.all(workers);
  return results;
}

export interface PushOptions {
  /** Manual button press: also runs when autoPush is off, and preserves unsaved editor edits. */
  manual?: boolean;
  /** Push even though GitHub has commits this project has not seen (overwrites them). */
  force?: boolean;
  /** The user's own commit message; used verbatim. Absent/blank -> the generated message. */
  message?: string;
}

async function performPush(link: LinkContext, opts: PushOptions): Promise<GithubPushResultDto> {
  const { owner, repo, branch } = link;

  // Editor edits that no version holds yet become their own USER version first,
  // so the commit still maps 1:1 onto a version.
  if (opts.manual) await snapshotUserEditsIfDirty(link.projectId);

  const project = await prisma.codeProject.findUnique({
    where: { id: link.projectId },
    select: { title: true, currentVersion: true, status: true },
  });
  if (!project) throw new ApiError("Project not found", STATUS_CODES.NOT_FOUND);
  if (project.status === "GENERATING") {
    throw new ApiError("The AI is still writing this project — push when it finishes", STATUS_CODES.CONFLICT);
  }

  const files = await readFiles(link.projectId);
  if (files.length === 0) {
    return { pushed: false, commitSha: null, commitUrl: null, fileCount: 0, skippedReason: "The project has no files yet" };
  }

  const versionRow = await prisma.codeProjectVersion.findUnique({
    where: { projectId_version: { projectId: link.projectId, version: project.currentVersion } },
    select: { plan: true, changedPaths: true, source: true },
  });

  const token = await getInstallationToken(link.connection.installationId);
  let head = await readRemoteHead(token, owner, repo, branch);

  // Remote-ahead guard: without it, the tree-without-base_tree strategy would
  // erase commits made on github.com since our last sync.
  if (!opts.force && head.sha && link.lastCommitSha && head.sha !== link.lastCommitSha) {
    throw Object.assign(
      new ApiError(
        `${REMOTE_AHEAD_MARK} GitHub has changes that are not in this project. Pull them first, or push to overwrite them.`,
        STATUS_CODES.CONFLICT,
      ),
      { code: "REMOTE_AHEAD" },
    );
  }

  if (head.repoEmpty) {
    const bootstrapSha = await bootstrapEmptyRepo(token, owner, repo, files[0]);
    head = { sha: bootstrapSha, repoEmpty: false };
  }

  const treeSha = await createTree(token, owner, repo, files);

  // Identical to what is already on the branch → no empty commit.
  if (head.sha) {
    const parent = await githubJson<{ tree: { sha: string } }>(`/repos/${owner}/${repo}/git/commits/${head.sha}`, { token });
    if (parent.tree.sha === treeSha) {
      await setSyncState(link.id, "IDLE", {
        lastCommitSha: head.sha,
        lastPushedVersion: project.currentVersion,
        lastSyncedAt: new Date(),
      });
      return { pushed: false, commitSha: head.sha, commitUrl: null, fileCount: files.length, skippedReason: "Already up to date" };
    }
  }

  const commit = await githubJson<{ sha: string; html_url: string }>(`/repos/${owner}/${repo}/git/commits`, {
    token,
    method: "POST",
    body: {
      message:
        opts.message?.trim() ||
        buildCommitMessage({
          version: project.currentVersion,
          title: project.title,
          plan: versionRow?.plan ?? null,
          changedPaths: versionRow?.changedPaths ?? [],
          source: versionRow?.source ?? "AI",
        }),
      tree: treeSha,
      parents: head.sha ? [head.sha] : [],
    },
  });

  if (head.sha) {
    const moved = await githubRaw(`/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(branch)}`, {
      token,
      method: "PATCH",
      body: { sha: commit.sha, force: !!opts.force },
    });
    if (!moved.ok) {
      if (moved.status === 422) {
        throw Object.assign(
          new ApiError(`${REMOTE_AHEAD_MARK} GitHub changed while pushing. Pull first, or push to overwrite.`, STATUS_CODES.CONFLICT),
          { code: "REMOTE_AHEAD" },
        );
      }
      throw new GithubHttpError("Could not update the branch on GitHub", STATUS_CODES.BAD_REQUEST, moved.status);
    }
  } else {
    await githubJson(`/repos/${owner}/${repo}/git/refs`, {
      token,
      method: "POST",
      body: { ref: `refs/heads/${branch}`, sha: commit.sha },
    });
  }

  await setSyncState(link.id, "IDLE", {
    lastCommitSha: commit.sha,
    lastPushedVersion: project.currentVersion,
    lastSyncedAt: new Date(),
  });
  return { pushed: true, commitSha: commit.sha, commitUrl: commit.html_url, fileCount: files.length };
}

/**
 * Runs a sync with SYNCING/ERROR bookkeeping around it. The header button
 * polls `syncState`, so every failure lands there as a readable `lastError`.
 */
async function withSyncState<T>(link: LinkContext, task: () => Promise<T>): Promise<T> {
  await setSyncState(link.id, "SYNCING");
  try {
    return await task();
  } catch (error: any) {
    const message = String(error?.message ?? "GitHub sync failed").slice(0, 500);
    await setSyncState(link.id, "ERROR", { lastError: message }).catch(() => undefined);
    throw error;
  }
}

/**
 * Manual push (button) — errors propagate to the caller so the UI can show them.
 */
export async function pushProject(projectId: number, opts: PushOptions = {}): Promise<GithubPushResultDto> {
  const link = await loadLink(projectId);
  if (!link || !link.connection.isActive) {
    throw new ApiError("This project is not linked to a GitHub repository", STATUS_CODES.NOT_FOUND);
  }
  return serialise(projectId, () => withSyncState(link, () => performPush(link, { ...opts, manual: opts.manual ?? true })));
}

/**
 * Auto-push after an AI turn. Fire-and-forget: it must never throw into, or
 * delay, the chat stream. Silently does nothing for the (common) case of a
 * project with no GitHub link, or a server without GitHub credentials.
 */
export async function pushAfterAiTurn(projectId: number): Promise<void> {
  try {
    if (!isGithubConfigured()) return;
    const link = await loadLink(projectId);
    if (!link || !link.connection.isActive || !link.autoPush) return;
    await serialise(projectId, () => withSyncState(link, () => performPush(link, { manual: false })));
  } catch (error: any) {
    // withSyncState already recorded it on the link for the UI.
    console.warn(`[github] auto-push failed project=${projectId}: ${error?.message ?? error}`);
  }
}

/* ------------------------------------------------------------------ *
 * Pull
 * ------------------------------------------------------------------ */

function extensionOf(path: string): string {
  const name = path.split("/").pop() ?? "";
  const dot = name.lastIndexOf(".");
  return dot === -1 ? "" : name.slice(dot + 1).toLowerCase();
}

async function performPull(link: LinkContext): Promise<GithubPullResultDto> {
  const { owner, repo, branch } = link;

  const project = await prisma.codeProject.findUnique({ where: { id: link.projectId }, select: { status: true } });
  if (!project) throw new ApiError("Project not found", STATUS_CODES.NOT_FOUND);
  if (project.status === "GENERATING") {
    throw new ApiError("The AI is still writing this project — pull when it finishes", STATUS_CODES.CONFLICT);
  }

  const token = await getInstallationToken(link.connection.installationId);
  const head = await readRemoteHead(token, owner, repo, branch);
  if (!head.sha) throw new ApiError("The GitHub repository has no commits to pull yet", STATUS_CODES.BAD_REQUEST);

  const commit = await githubJson<{ tree: { sha: string } }>(`/repos/${owner}/${repo}/git/commits/${head.sha}`, { token });
  const tree = await githubJson<{
    truncated: boolean;
    tree: { path: string; mode: string; type: string; sha: string; size?: number }[];
  }>(`/repos/${owner}/${repo}/git/trees/${commit.tree.sha}?recursive=1`, { token });
  if (tree.truncated) {
    throw new ApiError("This repository is too large to pull into the editor", STATUS_CODES.BAD_REQUEST);
  }

  const skipped: { path: string; reason: string }[] = [];
  const wanted: { path: string; sha: string }[] = [];
  for (const entry of tree.tree) {
    if (entry.type !== "blob") continue; // directories are implied by paths; submodules ("commit") are skipped
    if (entry.mode === "120000") {
      skipped.push({ path: entry.path, reason: "symlink" });
      continue;
    }
    const path = normalizeCodePath(entry.path);
    if (!path) {
      skipped.push({ path: entry.path, reason: "path not allowed (node_modules, .git, or unsafe)" });
      continue;
    }
    if (BINARY_EXTENSIONS.has(extensionOf(path))) {
      skipped.push({ path, reason: "binary file" });
      continue;
    }
    if ((entry.size ?? 0) > MAX_FILE_CHARS) {
      skipped.push({ path, reason: `larger than ${MAX_FILE_CHARS.toLocaleString()} characters` });
      continue;
    }
    if (wanted.length >= MAX_FILES_PER_PROJECT) {
      skipped.push({ path, reason: `project limit of ${MAX_FILES_PER_PROJECT} files reached` });
      continue;
    }
    wanted.push({ path, sha: entry.sha });
  }
  if (wanted.length === 0) {
    throw new ApiError("The repository has no importable text files", STATUS_CODES.BAD_REQUEST);
  }

  const downloaded = await mapLimit(wanted, BLOB_FETCH_CONCURRENCY, async (f) => {
    const blob = await githubJson<{ content: string; encoding: string }>(`/repos/${owner}/${repo}/git/blobs/${f.sha}`, { token });
    const raw = blob.encoding === "base64" ? Buffer.from(blob.content, "base64") : Buffer.from(blob.content, "utf8");
    return { path: f.path, buffer: raw };
  });

  const files: { path: string; content: string }[] = [];
  for (const d of downloaded) {
    // A NUL byte means binary content that slipped past the extension check.
    if (d.buffer.includes(0)) {
      skipped.push({ path: d.path, reason: "binary file" });
      continue;
    }
    const content = d.buffer.toString("utf8");
    if (content.length > MAX_FILE_CHARS) {
      skipped.push({ path: d.path, reason: `larger than ${MAX_FILE_CHARS.toLocaleString()} characters` });
      continue;
    }
    files.push({ path: d.path, content });
  }
  if (files.length === 0) throw new ApiError("The repository has no importable text files", STATUS_CODES.BAD_REQUEST);

  // Nothing is lost: unsaved editor edits become a version first, and the pull
  // itself is a new version, so the v-chip menu can always get back.
  await snapshotUserEditsIfDirty(link.projectId);
  await prisma.$transaction([
    prisma.codeFile.deleteMany({ where: { projectId: link.projectId } }),
    prisma.codeFile.createMany({
      data: files.map((f) => ({
        projectId: link.projectId,
        path: f.path,
        language: languageFromPath(f.path),
        content: f.content,
      })),
    }),
  ]);
  const version = await snapshotVersion(link.projectId, "GITHUB", {
    plan: `Pulled from GitHub (${owner}/${repo}@${head.sha.slice(0, 7)})`,
    changedPaths: files.map((f) => f.path),
  });

  await setSyncState(link.id, "IDLE", {
    lastCommitSha: head.sha,
    lastPushedVersion: version,
    lastSyncedAt: new Date(),
  });
  return { version, fileCount: files.length, commitSha: head.sha, skipped };
}

export async function pullProject(projectId: number): Promise<GithubPullResultDto> {
  const link = await loadLink(projectId);
  if (!link || !link.connection.isActive) {
    throw new ApiError("This project is not linked to a GitHub repository", STATUS_CODES.NOT_FOUND);
  }
  return serialise(projectId, () => withSyncState(link, () => performPull(link)));
}

/** Whether the remote branch has any commits — used before the first push to a non-empty repo. */
export async function remoteHasCommits(installationId: string, owner: string, repo: string, branch: string): Promise<boolean> {
  const token = await getInstallationToken(installationId);
  const head = await readRemoteHead(token, owner, repo, branch);
  return head.sha !== null;
}
